---
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@91054c3b9dc15fdc6a2f45be47405d891e672ef0
        with:
          cli: latest

      - name: Show Clojure env details
        run: clojure -Sdescribe

      - name: Lint with clj-kondo
        uses: DeLaGuardo/clojure-lint-action@f712330e03eec4daa36da7045213190083aca4dd
        with:
          clj-kondo-args: --lint src test
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run tests
        run: clojure -A:test
