---
name: macOS build

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup GraalVM CE
        uses: DeLaGuardo/setup-graalvm@4.0
        with:
          graalvm: '21.0.0.2'
          java: 'java11'

      - name: Setup native-image
        run: |
          gu install native-image

      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@91054c3b9dc15fdc6a2f45be47405d891e672ef0
        with:
          cli: latest

      - name: Show Clojure env details
        run: clojure -Sdescribe

      - name: Run tests
        run: clojure -M:test

      - name: Install upx
        run: brew install upx

      - name: Build native-image
        run: clojure -M:native-image

      - name: Smoke test the wernicke binary
        run: |
          printf '{"vpc-12345": "sg-12345"}' | ./wernicke

      - name: Run upx
        run: upx wernicke

      - uses: actions/upload-artifact@v2
        with:
          name: wernicke-macos
          path: wernicke
